<a href="https://colab.research.google.com/github/hesamhadadi/pytorch-deep-learning-labs/blob/main/labs/lab01_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals Exercises




### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch
x = torch.rand(7, 7)
print(x.shape)
# Create random tensor

torch.Size([7, 7])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
tensor=torch.rand(1, 7)
y1=tensor @ tensor.T
y2=tensor.matmul(tensor.T)

print("y1",y1)

print("y2",y2)
# Perform matrix multiplication



y1 tensor([[2.6292]])
y2 tensor([[2.6292]])


[link text](https://)### 4. Set the random seed to `0` and do 2 & 3 over again.

> Add blockquote



The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
import torch

# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor1 = torch.rand(7, 7)
tensor2 = torch.rand(1, 7)

# Matrix multiply (transpose second tensor)
result = tensor1 @ tensor2.T

print(result, result.shape)



# Matrix multiply tensors


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
import torch


if torch.cuda.is_available():
    torch.cuda.manual_seed(1234)
    torch.cuda.manual_seed_all(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
import torch

# Set random seed (CPU seed is fine here)
torch.manual_seed(1234)

# Check for GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

# Create two random tensors and send to GPU
tensor1 = torch.rand(2, 3).to(device)
tensor2 = torch.rand(2, 3).to(device)

print(tensor1)
print(tensor2)


Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
# Perform matrix multiplication on tensors from Q6
result = tensor1 @ tensor2.T

print(result, result.shape)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0') torch.Size([2, 2])




```
# This is formatted as code
```

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
max_value = result.max()

# Find min
min_value = result.min()

print("Max:", max_value)
print("Min:", min_value)

Max: tensor(0.5617, device='cuda:0')
Min: tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find argmax
argmax_value = result.argmax()

# Find argmin
argmin_value = result.argmin()

print("Argmax index:", argmax_value)
print("Argmin index:", argmin_value)


Argmax index: tensor(3, device='cuda:0')
Argmin index: tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
import torch

# Set seed to 7
torch.manual_seed(7)

# Create random tensor of shape (1, 1, 1, 10)
tensor1 = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor2 = tensor1.squeeze()

# Print tensors and their shapes
print(tensor1, tensor1.shape)
print(tensor2, tensor2.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
